### ISSUE TITLE
Queue Plays Every Other Video 

### ISSUE THREAD

**Issue by JO-Arden925** [Circularify/Queue-n-Play#2]
**Platform:** Windows 8.1
**Chrome Version:** 50.0.2661.102 m

**Steps to create problem:** 
1. Open a video
2. Start browsing so video is in the lower right-hand corner
3. Add multiple videos to the queue (I added four)
4. Watch the videos and let the playlist do its thing.

The Queue always skips the video that occupies the number 1 slot. So it ends up playing every other video in the playlist. 

![picture123](https://cloud.githubusercontent.com/assets/19352901/15479863/646363a4-20f0-11e6-8641-e0ecda5ddd6e.png)

**Comment by martijnlentink** [comment]
Hi Arden,

Thank you for your ongoing support for our products. We actually encountered this problem ourselves some days a go, but we did not come across the opportunity to post it to the Github. We really appreciate that you, again, take the time to give us feedback on Queue 'n Play. This will be the first issue that will be looked at for the next release of QnP!

The Circularify team

**Comment by JO-Arden925** [comment]
Sorry for not replying to your comments sooner. I've been traveling with my sister. But, I am happy to help! After all, by helping you with the next release of QnP, I also help myself :)

**Comment by dickwolff** [comment]
This bug has been fixed in the latest release.
