### ISSUE TITLE
Feedback on [Add to queue] button

### ISSUE THREAD

**Issue by twixr** [Circularify/Queue-n-Play#3]
First of all, I just installed your extension and it's fucking amazing. Compliments.

![image](https://cloud.githubusercontent.com/assets/5758900/23454620/1f6142ac-fe6d-11e6-974a-ae9a1d9d21b3.png)

If you hit the [Add to queue] button, you won't get any feedback of whatsoever. 
I think it would be nice to change the icon inside into a loader, and on success, it will change to a checkmark.
After some seconds, it should go back to it's original state (The plus icon)

Again, compliments for the nice work :-)

**Comment by dickwolff** [comment]
Hi Jesse,

Thank you for your praising words. 

Great suggestion, we'll look at a proper solution for informing our users that their queue operation succeeded. We'll update this issue when there are any updates concerning this feature.

**Comment by dickwolff** [comment]
Closing. Feature is implemented in the latest release, being 2.1.0. 

Release is being published to CWS as we speak.
