### ISSUE TITLE
Bug - Unable to add suggestions to queue after [Show more] button

### ISSUE THREAD

**Issue by twixr** [Circularify/Queue-n-Play#4]
In the right sidebar of Youtube, where the suggestions at, there is a [Show more] button at the bottom.
If you hit that, it will.. Well.. Show more (items).
But those items doesn't have the [Add to queue] button (icon) on it.

I think the GIF below will say enough :)

![mrt -02-2017 10-47-16](https://cloud.githubusercontent.com/assets/5758900/23501805/a76a34ec-ff35-11e6-8263-be04fdf7d5a1.gif)

**Comment by martijnlentink** [comment]
Hi Jesse,

Thank you for your active participation in making Queue 'n Play better. We were able to reproduce this bug and we will try to solve this issue as soon as possible.

**Comment by martijnlentink** [comment]
We've found the source of this issue and fixed it. It will be fixed in the next version of QnP.

**Comment by twixr** [comment]
That's awesome, thank you!
Do you know when the next release is? And is it possible to announce it in this issue as well? 
That way I'm able to download the new version immediately. 😃

**Comment by dickwolff** [comment]
When a release is published on the CWS, we will assign the milestone on the issues we fix.

**Comment by dickwolff** [comment]
Feature is implemented in the latest release, being 2.1.0. 

Release is being published to CWS as we speak.
