### ISSUE TITLE
Bug - Unable to use any other playlist

### ISSUE THREAD

**Issue by twixr** [Circularify/Queue-n-Play#5]
I was trying to listen to a playlist, when I noticed that it doesn't continue after the song is finished.
Turns out, playlists other than the queue 'n play, won't work.
Example playlist: https://www.youtube.com/watch?v=VDQHD8cD-VI&list=PLmU8B4gZ41ifU7C952drNuMMJ4O-PAuWv
It does work when the extension is not turned on, but when the extension is turned on, I cannot load the playlist.

Btw, it's too bad your project is not open-source. Would really like to help out, instead of making issues and do nothing about it.

**Comment by twixr** [comment]
How am I supposed to listen to my Taylor Swift playlist with this bug? :(

**Comment by dickwolff** [comment]
This issue was reported to us some time ago (in the CWS reporting tool), but we haven't been able to find a proper solution for this issue.

@jessereitsma In your opinion, what would be the expected behaviour when you load a YouTube playlist? Play that playlist in Queue 'n Play, side-load it and merge it with your own playlist? Or none of the before?

**Comment by twixr** [comment]
The expected behaviour in my opinion, is to only load the queue playlist when there is no other playlist.
Even better, only load the queue playlist when there is a minimum of one (1) item in it.
This way, it doesn't bother you with the big dark empty block.
You have the normal Youtube Experience. 
But when you add something to your queue, it will load up the queue playlist.
After your queue playlist is empty again, just hide (stop) the playlist.
If you have autoplay on (Youtube feature) let it do it's job (which is already the case now) and if it's off, don't do anything.

But when you open a playlist, it shouldn't use the queue at all.
You can check if the uri contains `list=` (for example)

**Comment by martijnlentink** [comment]
Hi there Jesse,

After some testing we ended up with just overriding your Queue n Playlist by the playlist provided from YT. In the future we will look into other options, but for now you can enjoy your Taylor Swift playlist again!

Martijn

**Comment by dickwolff** [comment]
Closing. Feature is implemented in the latest release, being 2.1.0. 

Release is being published to CWS as we speak.

**Comment by twixr** [comment]
Thank you for the fix.
However, it does not work fully.
When you have your own playlist, and you set it to private, it won't work.
It will play the first song, but it doesn't load the rest of the playlist in the queue.

**Comment by martijnlentink** [comment]
We didn't integrate private playlists into our test scenario. Once again, nice find exploring the edge cases for us. We will explore the possible fixes for this issue.

Again, thanks for your quick response and contribution.

**Comment by twixr** [comment]
No problem, I'm glad I can help in some way.
