### ISSUE TITLE
Youtube's new interface

### ISSUE THREAD

**Issue by twixr** [Circularify/Queue-n-Play#9]
Hey guys,

With the new interface / version of YouTube I am unable to add video's to my queue anymore.
It would be great to have support for this interface.

Although the new interface is not yet rolled out for everybody, it's possible to test it out with the following cookie:
```
document.cookie="VISITOR_INFO1_LIVE=fPQ4jCL6EiE"
```

Also, if you scroll down on the video page the video doesn't show up in the bottom-right corner.
But it does keep playing (and appear in the bottom-right corner box) when you leave the page and switch to another page within YouTube.

 -- Jesse

**Comment by martijnlentink** [comment]
Hi Jesse,

Thank you for your active support. We will investigate this issue and get back to you as soon as possible 👍 

Martijn

**Comment by martijnlentink** [comment]
Hey Jesse,

After some investigation we found that we need to restructure quite a lot code to fix this issue. Please bear with us while we fix this issue.

**Comment by twixr** [comment]
Ah ok, thanks for the update.
Success!

**Comment by tamasviktor** [comment]
Best extension ever, but now not works on new youtube design i hope guys can fix it. I like the new YT design but now need to use old one because Queue-n-Play works just it that.

**Comment by martijnlentink** [comment]
Thank you for your continuing support. As mentioned the new YT layout forces us to completely rewrite parts of our extension, we started a part of this but caught up in work while doing it. We will keep you updated.
